### PR TITLE
some more tweeks before customer demo

### PR DESCRIPTION
**Pull request by anthonyBosek**
abosek 02/22/2023 a few mods

### CODE REVIEW

**Review by anthonyBosek — COMMENTED** [review]
abosek 02/28/2023 reviewed this from last week

**Review by anthonyBosek — COMMENTED** [review]
abosek 02/28/2023 several changes to app prior to presentation, all clear in testing

**Review by anthonyBosek — COMMENTED** [review]
jamie?? hello, you there??

**Review by jamiefrazier — APPROVED** [review]
reviewed and approved.

**Review by anthonyBosek — COMMENTED** [review]
abosek 03/11/2023

**Pull request merged**
